name: Release & Publish to NPM
on:
  push:
    branches:
      - 'main'
jobs: 
    release:
        runs-on: ubuntu-20.04
        permissions:
          contents: read
          packages: write
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Set Node.js 18.x
              uses: actions/setup-node@v3
              with:
                node-version: 18.x

            - name: Initialize Git user
              run: |
                 git config --global user.email "keumks0331@gmail.com"
                 git config --global user.name "Release Workflow"
            - name: Run install
              uses: borales/actions-yarn@v4
              with:
                cmd: install
            - name: Run release
              uses: borales/actions-yarn@v4
              with:
                cmd: release --ci
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                NODE_AUTH_TOKEN : ${{ secrets.NPM_TOKEN }}
            